/*
* INSTITUTO POLITECNICO NACIONAL
* ESCUELA SUPERIOR DE COMPUTO
* APLICACIONES PARA COMUNICACIONES EN RED
* 
* Bautista Rosales Sandra Ivette
*
* Arellano Cristopher
* Hernandez Marco
*/
package com.cliente;

import com.modelo.Producto;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Cliente extends javax.swing.JFrame {

    ArrayList<Producto> Productos;
    Socket cl;
    private ObjectOutputStream oos;
    private ObjectInputStream ois;
    private ObjectInputStream oisO;
    private ArrayList<Producto> reporte;
    private Producto[]p;

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        this.setLocationRelativeTo(null);
        initComponents();
        ButtontennisAdidas.setEnabled(false);
        ButtontennisJordan.setEnabled(false);
        ButtonbalonAdidas.setEnabled(false);
        tennisNMercurial.setEnabled(false);
        ButtonReporte.setEnabled(false);
        ButtonComprar.setEnabled(false);
        ButtonBorrar.setEnabled(false);
        ButtonDesconectar.setEnabled(false);
    }

    private void abrirSocket(String serverAdress) {
        try {
            cl = new Socket(serverAdress, 1234);
            ButtontennisAdidas.setEnabled(true);
            ButtontennisJordan.setEnabled(true);
            ButtonbalonAdidas.setEnabled(true);
            tennisNMercurial.setEnabled(true);
            ButtonConectar.setEnabled(false);
            ButtonDesconectar.setEnabled(true);
            ButtonBorrar.setEnabled(true);
            ButtonComprar.setEnabled(true);
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    public void conecta() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        ButtontennisAdidas = new javax.swing.JButton();
        ButtontennisJordan = new javax.swing.JButton();
        ButtonbalonAdidas = new javax.swing.JButton();
        tennisNMercurial = new javax.swing.JButton();
        ButtonConectar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        ButtonBorrar = new javax.swing.JButton();
        ButtonComprar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonDesconectar = new javax.swing.JButton();
        JLabel = new javax.swing.JLabel();
        ButtonReporte = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtontennisAdidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ico/tennisAdidas.png"))); // NOI18N
        ButtontennisAdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtontennisAdidasActionPerformed(evt);
            }
        });

        ButtontennisJordan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ico/tennisJordan.png"))); // NOI18N
        ButtontennisJordan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtontennisJordanActionPerformed(evt);
            }
        });

        ButtonbalonAdidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ico/balonAdidas.png"))); // NOI18N
        ButtonbalonAdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonbalonAdidasActionPerformed(evt);
            }
        });

        tennisNMercurial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ico/tennisNMercurial.png"))); // NOI18N
        tennisNMercurial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tennisNMercurialActionPerformed(evt);
            }
        });

        ButtonConectar.setText("Conectar");
        ButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConectarActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setResizable(false);
            tblProductos.getColumnModel().getColumn(1).setResizable(false);
            tblProductos.getColumnModel().getColumn(2).setResizable(false);
        }

        ButtonBorrar.setText("Borrar Elemento");
        ButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBorrarActionPerformed(evt);
            }
        });

        ButtonComprar.setText("Confirmar Compra");
        ButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonComprarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Compras");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Catálogo");

        ButtonDesconectar.setText("Desconectarse");
        ButtonDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDesconectarActionPerformed(evt);
            }
        });

        ButtonReporte.setText("Generar ticket");
        ButtonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReporteActionPerformed(evt);
            }
        });

        jLabel3.setText("Tienda Deportiva Crstopher y Marco");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtontennisAdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(ButtonbalonAdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButtontennisJordan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tennisNMercurial, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButtonComprar)
                                    .addComponent(ButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(ButtonDesconectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(ButtonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)))
                .addComponent(JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(459, 459, 459)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ButtonbalonAdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(ButtontennisAdidas, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ButtontennisJordan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tennisNMercurial, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ButtonReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonComprar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ButtonConectar)
                                    .addComponent(ButtonDesconectar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)))))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConectarActionPerformed
        String serverAdress;
        serverAdress = JOptionPane.showInputDialog(null, "Introduce la dirección del servidor");
        abrirSocket(serverAdress);
    }//GEN-LAST:event_ButtonConectarActionPerformed

    private void ButtontennisAdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtontennisAdidasActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.addRow(new Object[]{"Tennis Adidas", 1000.00, 01});
        String path = "tennisAdidas.jpg";
        try {
            BufferedImage buffImage = ImageIO.read(new File(path));
            JLabel.setIcon(new ImageIcon(buffImage));
            JLabel.repaint();
        } catch (IOException ex) {
            System.out.println("No se puede leer la imagen");
        }

    }//GEN-LAST:event_ButtontennisAdidasActionPerformed

    private void ButtontennisJordanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtontennisJordanActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.addRow(new Object[]{"Tennis Jordan", 3500.00, 02});
        String path = "tennisJordan.jpg";
        try {
            BufferedImage buffImage = ImageIO.read(new File(path));
            JLabel.setIcon(new ImageIcon(buffImage));
            JLabel.repaint();
        } catch (IOException ex) {
            System.out.println("No se puede leer la imagen");
        }
    }//GEN-LAST:event_ButtontennisJordanActionPerformed

    private void ButtonbalonAdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonbalonAdidasActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.addRow(new Object[]{"Balon Champions League", 700.00, 03});
        String path = "balonChampions.jpg";
        try {
            BufferedImage buffImage = ImageIO.read(new File(path));
            JLabel.setIcon(new ImageIcon(buffImage));
            JLabel.repaint();
        } catch (IOException ex) {
            System.out.println("No se puede leer la imagen");
        }
    }//GEN-LAST:event_ButtonbalonAdidasActionPerformed

    private void tennisNMercurialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tennisNMercurialActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        model.addRow(new Object[]{"Tacos Nike Mercurial", 3000.00, 04});
        String path = "tennisNMercurial.jpg";
        try {
            BufferedImage buffImage = ImageIO.read(new File(path));
            JLabel.setIcon(new ImageIcon(buffImage));
            JLabel.repaint();
        } catch (IOException ex) {
            System.out.println("No se puede leer la imagen");
        }
    }//GEN-LAST:event_tennisNMercurialActionPerformed

    private void ButtonDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDesconectarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        try {
            cl.close();
            ButtonConectar.setEnabled(true);
            ButtontennisAdidas.setEnabled(false);
            ButtontennisJordan.setEnabled(false);
            ButtonbalonAdidas.setEnabled(false);
            tennisNMercurial.setEnabled(false);
            ButtonComprar.setEnabled(false);
            ButtonBorrar.setEnabled(false);

        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ButtonDesconectarActionPerformed

    private void ButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBorrarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        if (tblProductos.getSelectedRow() == -1) {
            if (tblProductos.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Necesitas seleccionar lo que desea eliminar");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Necesitas seleccionar lo que desea eliminar");
            }
        } else {
            model.removeRow(tblProductos.getSelectedRow());
        }
    }//GEN-LAST:event_ButtonBorrarActionPerformed

    private void ButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonComprarActionPerformed
        // TODO add your handling code here:
        int numeroCompras = 0;
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();
        numeroCompras = model.getRowCount();
        ArrayList<Integer> compras = new ArrayList<Integer>(numeroCompras);
        if (tblProductos.getRowCount() == 0) {
            JOptionPane.showMessageDialog(rootPane, "No has comprado nada :(");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Tienes " + model.getRowCount() + " articulos en tu carrito.");
            for (int i = 0; i < numeroCompras; i++) {
                System.out.println("Id articulo comprado: " + (int) model.getValueAt(i, 2));
                compras.add((int) model.getValueAt(i, 2));
            }

            //Seteamos el tamaño del arraylist de las compras
            this.reporte = new ArrayList<Producto>(compras.size());
            try {
                oos = new ObjectOutputStream(cl.getOutputStream());
                oos.writeObject(compras);
                oos.flush();
            } catch (IOException e) {
                e.printStackTrace();
            }

            try {
                ois = new ObjectInputStream(cl.getInputStream());
                
                reporte = (ArrayList<Producto>) ois.readObject();
            
            } catch (IOException e) {
                e.printStackTrace();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }

            ButtonReporte.setEnabled(true);
        }
    }//GEN-LAST:event_ButtonComprarActionPerformed

    private void ButtonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReporteActionPerformed
        new Tiquet(reporte).setVisible(true);
    }//GEN-LAST:event_ButtonReporteActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBorrar;
    private javax.swing.JButton ButtonComprar;
    private javax.swing.JButton ButtonConectar;
    private javax.swing.JButton ButtonDesconectar;
    private javax.swing.JButton ButtonReporte;
    private javax.swing.JButton ButtonbalonAdidas;
    private javax.swing.JButton ButtontennisAdidas;
    private javax.swing.JButton ButtontennisJordan;
    private javax.swing.JLabel JLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JButton tennisNMercurial;
    // End of variables declaration//GEN-END:variables
}
